export type Category = "muzqaymoq" | "ovqat";

export type CustomerType = "individual" | "shop";

export interface Product {
  id: string;
  name: string;
  brand: string;
  category: Category;
  categoryLabel: string;
  price: number;
  boxQty: number;
  boxPrice: number;
  weight: string;
  unit: string;
  image: string;
  images: string[];
  description: string;
  descriptionFull: string;
  tags: string[];
  isNew?: boolean;
  isPremium?: boolean;
  minOrder?: number;
}

export const PRODUCTS: Product[] = [
  // ═══════════════════════════════════════════════
  //  MUZQAYMOQ (Ice Cream)
  // ═══════════════════════════════════════════════

  // ─── BissGo Premium Bars ───
  {
    id: "bissgo-choc-peanut",
    name: "BissGo Chocolate Peanut",
    brand: "BissGo",
    category: "muzqaymoq",
    categoryLabel: "Premium Bar",
    price: 8200,
    boxQty: 36,
    boxPrice: 295200,
    weight: "90g",
    unit: "dona",
    image: "/products/p2_img4.jpeg",
    images: ["/products/p2_img4.jpeg", "/products/p2_img1.jpeg"],
    description: "Shokoladli qobiqli marojni, krunchi yeryong'oq bilan",
    descriptionFull: "A rich chocolate ice cream bar pokritiy thick chocolate coating with crunchy peanut pieces. Intense, bold, and perfectly textured for true chocolate lovers. Har bir tishlashda shokoladning to'liq ta'mini va yeryong'oqning hidi seziladi.",
    tags: ["shokolad", "yeryong'oq", "premium"],
    isPremium: true,
  },
  {
    id: "bissgo-vanilla-almond",
    name: "BissGo Vanilla Almond",
    brand: "BissGo",
    category: "muzqaymoq",
    categoryLabel: "Premium Bar",
    price: 8200,
    boxQty: 36,
    boxPrice: 295200,
    weight: "90g",
    unit: "dona",
    image: "/products/p2_img5.jpeg",
    images: ["/products/p2_img5.jpeg", "/products/p2_img1.jpeg"],
    description: "Vanil marojni, shokolad qobiq va bodom bilan",
    descriptionFull: "Smooth vanilla ice cream covered in a crunchy chocolate shell with roasted almond pieces. A refined balance of creaminess and nutty texture.",
    tags: ["vanil", "bodom", "premium"],
    isPremium: true,
  },
  {
    id: "bissgo-vanilla-caramel",
    name: "BissGo Vanilla Caramel",
    brand: "BissGo",
    category: "muzqaymoq",
    categoryLabel: "Premium Bar",
    price: 8200,
    boxQty: 36,
    boxPrice: 295200,
    weight: "90g",
    unit: "dona",
    image: "/products/p2_img6.jpeg",
    images: ["/products/p2_img6.jpeg", "/products/p2_img1.jpeg"],
    description: "Karamel tortmali vanil marojni",
    descriptionFull: "Delicate vanilla ice cream wrapped in a silky chocolate coating with a hint of caramel sweetness. Soft, smooth, and indulgently satisfying.",
    tags: ["vanil", "karamel", "premium"],
    isPremium: true,
  },
  {
    id: "bissgo-cream-brulee",
    name: "BissGo Cream Brulée",
    brand: "BissGo",
    category: "muzqaymoq",
    categoryLabel: "Premium Bar",
    price: 7000,
    boxQty: 20,
    boxPrice: 140000,
    weight: "110g",
    unit: "dona",
    image: "/products/p2_img7.jpeg",
    images: ["/products/p2_img7.jpeg"],
    description: "Karamel va Cream Brulée ta'mli premium marojni",
    descriptionFull: "Classic cream brulée flavor in a luxurious ice cream format. Rich caramel notes with a signature burned sugar finish.",
    tags: ["cream brulee", "karamel", "premium"],
    isPremium: true,
  },
  {
    id: "bissgo-vanilla-classic",
    name: "BissGo Vanilla Classic",
    brand: "BissGo",
    category: "muzqaymoq",
    categoryLabel: "Premium Bar",
    price: 7000,
    boxQty: 20,
    boxPrice: 140000,
    weight: "110g",
    unit: "dona",
    image: "/products/p2_img8.jpeg",
    images: ["/products/p2_img8.jpeg"],
    description: "Klassik vanil ta'mli konus marojni",
    descriptionFull: "Pure classic vanilla in a premium cone format. Simple, timeless, and always satisfying.",
    tags: ["vanil", "klassik", "konus"],
    isPremium: true,
  },
  // ─── BissGo Creamy Cup ───
  {
    id: "bissgo-creamy-vanilla",
    name: "BissGo Creamy Vanilla",
    brand: "BissGo",
    category: "muzqaymoq",
    categoryLabel: "Kremli Cup",
    price: 6900,
    boxQty: 28,
    boxPrice: 193200,
    weight: "100g",
    unit: "dona",
    image: "/products/p3_img4.jpeg",
    images: ["/products/p3_img4.jpeg", "/products/p3_img1.jpeg"],
    description: "Sof kremli vanil marojni, cup formatida",
    descriptionFull: "Pure creamy vanilla crafted for true dessert lovers. Experience the perfect balance of smoothness and sweetness.",
    tags: ["vanil", "kremli", "cup"],
    isPremium: true,
  },
  {
    id: "bissgo-coffee-vanilla",
    name: "BissGo Coffee Vanilla",
    brand: "BissGo",
    category: "muzqaymoq",
    categoryLabel: "Kremli Cup",
    price: 6900,
    boxQty: 28,
    boxPrice: 193200,
    weight: "100g",
    unit: "dona",
    image: "/products/p3_img5.jpeg",
    images: ["/products/p3_img5.jpeg", "/products/p3_img1.jpeg"],
    description: "Qahva va vanil aralash kremli marojni",
    descriptionFull: "Rich coffee fused with vanilla, made to satisfy every craving. Qahva va vanil — ikki ajoyib ta'mning uyg'unligi.",
    tags: ["qahva", "vanil", "cup"],
    isPremium: true,
  },
  // ─── BissGo Mini ───
  {
    id: "bissgo-mini-caramel",
    name: "BissGo Vanilla Caramel Mini",
    brand: "BissGo",
    category: "muzqaymoq",
    categoryLabel: "Mini Format",
    price: 5200,
    boxQty: 50,
    boxPrice: 260000,
    weight: "45g",
    unit: "dona",
    image: "/products/p3_img6.jpeg",
    images: ["/products/p3_img6.jpeg"],
    description: "Kichik formatdagi karamel vanil marojni",
    descriptionFull: "Vanilla caramel mini — bite-sized perfection. All the rich caramel and vanilla goodness in a convenient mini format.",
    tags: ["vanil", "karamel", "mini"],
  },
  {
    id: "bissgo-mini-bounty",
    name: "BissGo Bounty Coconut Mini",
    brand: "BissGo",
    category: "muzqaymoq",
    categoryLabel: "Mini Format",
    price: 5200,
    boxQty: 50,
    boxPrice: 260000,
    weight: "45g",
    unit: "dona",
    image: "/products/p3_img7.jpeg",
    images: ["/products/p3_img7.jpeg"],
    description: "Kokos va shokolad ta'mli mini marojni",
    descriptionFull: "Coconut and chocolate in perfect mini harmony. Tropical sweetness in every bite.",
    tags: ["kokos", "shokolad", "mini"],
  },
  {
    id: "bissgo-mini-fruity",
    name: "BissGo Fruity Mix Mini",
    brand: "BissGo",
    category: "muzqaymoq",
    categoryLabel: "Mini Format",
    price: 5200,
    boxQty: 50,
    boxPrice: 260000,
    weight: "45g",
    unit: "dona",
    image: "/products/p3_img8.jpeg",
    images: ["/products/p3_img8.jpeg"],
    description: "Mevali aralash mini marojni to'plami",
    descriptionFull: "A colorful fruity mix in mini format. Multiple fruit flavors packed into each box.",
    tags: ["meva", "aralash", "mini"],
  },
  // ─── BissGo Organic ───
  {
    id: "organic-persik",
    name: "BissGo Organic Persik-Marakuya",
    brand: "BissGo Organic",
    category: "muzqaymoq",
    categoryLabel: "Organic Bar",
    price: 3850,
    boxQty: 40,
    boxPrice: 154000,
    weight: "80g",
    unit: "dona",
    image: "/products/p4_img3.jpeg",
    images: ["/products/p4_img3.jpeg", "/products/p4_img1.jpeg"],
    description: "100% tabiiy shaftoli va marakuya sharbatidan",
    descriptionFull: "A refreshing fruit ice bar made with 100% natural peach and passion fruit. Fat-free and sugar-free.",
    tags: ["organic", "shaftoli", "marakuya", "yog'siz"],
    isNew: true,
  },
  {
    id: "organic-granat",
    name: "BissGo Organic Granat-Malina",
    brand: "BissGo Organic",
    category: "muzqaymoq",
    categoryLabel: "Organic Bar",
    price: 3850,
    boxQty: 40,
    boxPrice: 154000,
    weight: "80g",
    unit: "dona",
    image: "/products/p4_img4.jpeg",
    images: ["/products/p4_img4.jpeg", "/products/p4_img1.jpeg"],
    description: "Anor va malina sharbatidan organik muz bar",
    descriptionFull: "Pomegranate and raspberry combined in a refreshing organic ice bar.",
    tags: ["organic", "anor", "malina", "yog'siz"],
    isNew: true,
  },
  {
    id: "organic-kivi",
    name: "BissGo Organic Kivi",
    brand: "BissGo Organic",
    category: "muzqaymoq",
    categoryLabel: "Organic Bar",
    price: 3850,
    boxQty: 40,
    boxPrice: 154000,
    weight: "80g",
    unit: "dona",
    image: "/products/p4_img5.jpeg",
    images: ["/products/p4_img5.jpeg", "/products/p4_img1.jpeg"],
    description: "Yangilantiruvchi kivi mevali muz bar",
    descriptionFull: "Kiwi-flavored organic ice bar bursting with fresh tropical taste.",
    tags: ["organic", "kivi", "yog'siz"],
    isNew: true,
  },
  {
    id: "organic-limon",
    name: "BissGo Organic Limon-Apelsin",
    brand: "BissGo Organic",
    category: "muzqaymoq",
    categoryLabel: "Organic Bar",
    price: 3850,
    boxQty: 40,
    boxPrice: 154000,
    weight: "80g",
    unit: "dona",
    image: "/products/p4_img6.jpeg",
    images: ["/products/p4_img6.jpeg", "/products/p4_img1.jpeg"],
    description: "Limon va apelsin aralash yangilantiruvchi bar",
    descriptionFull: "Lemon and orange citrus blend in a refreshing organic ice bar.",
    tags: ["organic", "limon", "apelsin", "yog'siz"],
    isNew: true,
  },
  // ─── RAIS Cones ───
  {
    id: "rais-choc-peanut",
    name: "RAIS Chocolate & Peanut",
    brand: "RAIS",
    category: "muzqaymoq",
    categoryLabel: "Konus",
    price: 5750,
    boxQty: 20,
    boxPrice: 115000,
    weight: "65g",
    unit: "dona",
    image: "/products/p5_img2.jpeg",
    images: ["/products/p5_img2.jpeg", "/products/p5_img1.jpeg"],
    description: "Shokolad va yeryong'oqli premium konus",
    descriptionFull: "Chocolate and peanut combination in a premium RAIS cone. Thick chocolate coating, crunchy cone, and creamy chocolate ice cream.",
    tags: ["shokolad", "yeryong'oq", "konus"],
    isNew: true,
  },
  {
    id: "rais-vanilla",
    name: "RAIS Classic Vanilla",
    brand: "RAIS",
    category: "muzqaymoq",
    categoryLabel: "Konus",
    price: 5750,
    boxQty: 20,
    boxPrice: 115000,
    weight: "65g",
    unit: "dona",
    image: "/products/p5_img3.jpeg",
    images: ["/products/p5_img3.jpeg", "/products/p5_img1.jpeg"],
    description: "Klassik vanil ta'mli premium konus",
    descriptionFull: "Smooth vanilla ice cream wrapped in a thick chocolate coating inside a crunchy cone.",
    tags: ["vanil", "klassik", "konus"],
    isNew: true,
  },
  {
    id: "rais-banana",
    name: "RAIS Banana",
    brand: "RAIS",
    category: "muzqaymoq",
    categoryLabel: "Konus",
    price: 5750,
    boxQty: 20,
    boxPrice: 115000,
    weight: "65g",
    unit: "dona",
    image: "/products/p5_img4.jpeg",
    images: ["/products/p5_img4.jpeg", "/products/p5_img1.jpeg"],
    description: "Banan ta'mli shokoladli konus marojni",
    descriptionFull: "Soft banana-flavored ice cream covered in a rich chocolate glaze inside a crunchy cone.",
    tags: ["banan", "shokolad", "konus"],
    isNew: true,
  },
  {
    id: "rais-berries",
    name: "RAIS Forest Berries",
    brand: "RAIS",
    category: "muzqaymoq",
    categoryLabel: "Konus",
    price: 5750,
    boxQty: 20,
    boxPrice: 115000,
    weight: "65g",
    unit: "dona",
    image: "/products/p5_img5.jpeg",
    images: ["/products/p5_img5.jpeg", "/products/p5_img1.jpeg"],
    description: "O'rmon mevalari ta'mli konus marojni",
    descriptionFull: "A refreshing blend of wild berries inside a rich chocolate-coated cone.",
    tags: ["meva", "o'rmon", "konus"],
    isNew: true,
  },
  // ─── My Love Gelato Cup ───
  {
    id: "mylove-caramel",
    name: "My Love Karamel",
    brand: "My Love",
    category: "muzqaymoq",
    categoryLabel: "Gelato Cup",
    price: 7550,
    boxQty: 27,
    boxPrice: 203850,
    weight: "100g",
    unit: "dona",
    image: "/products/p8_img2.jpeg",
    images: ["/products/p8_img2.jpeg", "/products/p8_img1.jpeg"],
    description: "Karamel ta'mli kremli gelato, cup formatida",
    descriptionFull: "Black & White gelato with caramel — creamy, indulgent, and perfectly balanced. Har bir qoshiqda karamelning yoqimli ta'mi.",
    tags: ["karamel", "gelato", "cup"],
    isPremium: true,
  },
  {
    id: "mylove-vanilla",
    name: "My Love Vanil",
    brand: "My Love",
    category: "muzqaymoq",
    categoryLabel: "Gelato Cup",
    price: 7550,
    boxQty: 27,
    boxPrice: 203850,
    weight: "100g",
    unit: "dona",
    image: "/products/p8_img4.jpeg",
    images: ["/products/p8_img4.jpeg", "/products/p8_img1.jpeg"],
    description: "Vanil va shokolad aralash gelato cup",
    descriptionFull: "With Waffles & Chocolate — vanilla gelato with rich chocolate swirls and crispy waffle pieces.",
    tags: ["vanil", "shokolad", "gelato", "cup"],
    isPremium: true,
  },
  {
    id: "mylove-pistachio",
    name: "My Love Fistiq",
    brand: "My Love",
    category: "muzqaymoq",
    categoryLabel: "Gelato Cup",
    price: 7550,
    boxQty: 27,
    boxPrice: 203850,
    weight: "100g",
    unit: "dona",
    image: "/products/p8_img6.jpeg",
    images: ["/products/p8_img6.jpeg", "/products/p8_img1.jpeg"],
    description: "Fistiq ta'mli premium gelato cup",
    descriptionFull: "Rich pistachio gelato with a naturally nutty flavor. Smooth texture and refined taste.",
    tags: ["fistiq", "gelato", "cup", "premium"],
    isPremium: true,
  },
  // ─── Alfetto Cup ───
  {
    id: "alfetto-mango",
    name: "Alfetto Mango",
    brand: "Alfetto",
    category: "muzqaymoq",
    categoryLabel: "Kremli Cup",
    price: 7550,
    boxQty: 24,
    boxPrice: 181200,
    weight: "100g",
    unit: "dona",
    image: "/products/p9_img2.jpeg",
    images: ["/products/p9_img2.jpeg", "/products/p9_img1.jpeg"],
    description: "Sochli mango ta'mli kremli marojni cup",
    descriptionFull: "Fresh mango sorbet-style creamy ice cream in a convenient cup. Tropical, refreshing, and naturally sweet.",
    tags: ["mango", "kremli", "cup"],
  },
  {
    id: "alfetto-berries",
    name: "Alfetto O'rmon Mevalari",
    brand: "Alfetto",
    category: "muzqaymoq",
    categoryLabel: "Kremli Cup",
    price: 7550,
    boxQty: 24,
    boxPrice: 181200,
    weight: "100g",
    unit: "dona",
    image: "/products/p9_img3.jpeg",
    images: ["/products/p9_img3.jpeg", "/products/p9_img1.jpeg"],
    description: "O'rmon mevalari ta'mli kremli marojni",
    descriptionFull: "A vibrant blend of wild berries in creamy ice cream. Tangy, sweet, and refreshing.",
    tags: ["meva", "o'rmon", "kremli", "cup"],
  },
  {
    id: "alfetto-plombir",
    name: "Alfetto Plombir Premium",
    brand: "Alfetto",
    category: "muzqaymoq",
    categoryLabel: "Kremli Cup",
    price: 7550,
    boxQty: 24,
    boxPrice: 181200,
    weight: "100g",
    unit: "dona",
    image: "/products/p9_img5.jpeg",
    images: ["/products/p9_img5.jpeg", "/products/p9_img1.jpeg"],
    description: "Premium plombir marojni, an'anaviy ta'm",
    descriptionFull: "Classic plombir premium ice cream — rich, creamy, and made from natural ingredients. A timeless Soviet-inspired favorite.",
    tags: ["plombir", "kremli", "premium"],
    isPremium: true,
  },
  // ─── Wendy Premium 500g ───
  {
    id: "wendy-peach",
    name: "Wendy Shaftoli",
    brand: "Wendy",
    category: "muzqaymoq",
    categoryLabel: "Premium 500g",
    price: 25350,
    boxQty: 8,
    boxPrice: 202800,
    weight: "500g",
    unit: "quti",
    image: "/products/p10_img2.jpeg",
    images: ["/products/p10_img2.jpeg", "/products/p10_img1.jpeg"],
    description: "Shaftoli murabboli premium marojni, 500g",
    descriptionFull: "Premium ice cream with rich peach jam swirls. Fruity sweetness meets creamy richness in every spoonful.",
    tags: ["shaftoli", "premium", "500g"],
    isPremium: true,
  },
  {
    id: "wendy-vanilla",
    name: "Wendy Vanil",
    brand: "Wendy",
    category: "muzqaymoq",
    categoryLabel: "Premium 500g",
    price: 25350,
    boxQty: 8,
    boxPrice: 202800,
    weight: "500g",
    unit: "quti",
    image: "/products/p10_img3.jpeg",
    images: ["/products/p10_img3.jpeg", "/products/p10_img1.jpeg"],
    description: "Klassik vanil ta'mli premium marojni, 500g",
    descriptionFull: "Classic vanilla premium ice cream in a 500g family pack. Smooth, creamy, and always satisfying.",
    tags: ["vanil", "klassik", "500g"],
    isPremium: true,
  },
  // ─── Bambuk Fruit Ice ───
  {
    id: "bambuk-fruit-ice",
    name: "Bambuk Muz Bar",
    brand: "Bambuk",
    category: "muzqaymoq",
    categoryLabel: "Mevali Muz",
    price: 1950,
    boxQty: 40,
    boxPrice: 78000,
    weight: "90g",
    unit: "dona",
    image: "/products/p13_img2.jpeg",
    images: ["/products/p13_img2.jpeg", "/products/p13_img1.jpeg"],
    description: "Mevali muz bar — kivi, vишня, smородina, tarvuz (assorted)",
    descriptionFull: "Refreshing fruit ice bars in 4 flavors: Kiwi & Pineapple, Cherry, Blackcurrant & Blueberry, Watermelon & Melon. Light, fruity, and perfect for hot days.",
    tags: ["meva", "muz", "yog'siz"],
    isNew: true,
  },
  {
    id: "bambuk-mini",
    name: "Bambuk Mini Muz Bar",
    brand: "Bambuk",
    category: "muzqaymoq",
    categoryLabel: "Mevali Muz Mini",
    price: 3850,
    boxQty: 60,
    boxPrice: 78000,
    weight: "60g",
    unit: "dona",
    image: "/products/p13_img3.jpeg",
    images: ["/products/p13_img3.jpeg", "/products/p13_img1.jpeg"],
    description: "Kichik formatdagi mevali muz bar, assorted",
    descriptionFull: "Bite-sized fruit ice bars in the same 4 flavors. Perfect for children and sharing.",
    tags: ["meva", "muz", "mini", "yog'siz"],
    isNew: true,
  },
  // ─── BissGo Italian Gelato 300ml ───
  {
    id: "gelato-mango",
    name: "BissGo Gelato Mango & Marakuja",
    brand: "BissGo",
    category: "muzqaymoq",
    categoryLabel: "Italian Gelato",
    price: 32500,
    boxQty: 9,
    boxPrice: 292500,
    weight: "300ml",
    unit: "dona",
    image: "/products/p7_img8.jpeg",
    images: ["/products/p7_img8.jpeg", "/products/p7_img1.jpeg"],
    description: "Mango va marakuya ta'mli Italian gelato",
    descriptionFull: "A tropical fusion of ripe mango and exotic passion fruit, crafted in smooth Italian gelato style.",
    tags: ["mango", "marakuya", "gelato", "premium"],
    isNew: true,
    isPremium: true,
  },
  {
    id: "gelato-pistachio",
    name: "BissGo Gelato Pistachio",
    brand: "BissGo",
    category: "muzqaymoq",
    categoryLabel: "Italian Gelato",
    price: 32500,
    boxQty: 9,
    boxPrice: 292500,
    weight: "300ml",
    unit: "dona",
    image: "/products/p7_img9.jpeg",
    images: ["/products/p7_img9.jpeg", "/products/p7_img1.jpeg"],
    description: "Fistiq ta'mli kremli Italian gelato",
    descriptionFull: "Rich and creamy pistachio gelato with a naturally nutty flavor.",
    tags: ["fistiq", "gelato", "premium"],
    isNew: true,
    isPremium: true,
  },
  {
    id: "gelato-caramel-nuts",
    name: "BissGo Gelato Caramel & Nuts",
    brand: "BissGo",
    category: "muzqaymoq",
    categoryLabel: "Italian Gelato",
    price: 32500,
    boxQty: 9,
    boxPrice: 292500,
    weight: "300ml",
    unit: "dona",
    image: "/products/p7_img10.jpeg",
    images: ["/products/p7_img10.jpeg", "/products/p7_img1.jpeg"],
    description: "Karamel va yong'oqli Italian gelato",
    descriptionFull: "A luxurious blend of silky caramel and crunchy nuts in a creamy gelato base.",
    tags: ["karamel", "yong'oq", "gelato", "premium"],
    isNew: true,
    isPremium: true,
  },
  // ─── 1kg Bulk ───
  {
    id: "gallant-cookies",
    name: "Gallant Cookies Ice Cream",
    brand: "Gallant",
    category: "muzqaymoq",
    categoryLabel: "1kg Format",
    price: 42900,
    boxQty: 6,
    boxPrice: 257400,
    weight: "1kg",
    unit: "quti",
    image: "/products/p12_img1.jpeg",
    images: ["/products/p12_img1.jpeg", "/products/p12_img4.jpeg"],
    description: "Pechene bo'laklari bilan kremli marojni, 1kg",
    descriptionFull: "Creamy ice cream enriched with crunchy cookie pieces. A classic combination for do'konlar and big events.",
    tags: ["pechene", "kremli", "1kg", "do'kon"],
    isPremium: true,
  },
  {
    id: "fruit-freddo",
    name: "Fruit Freddo Cherry & Chocolate",
    brand: "Fruit Freddo",
    category: "muzqaymoq",
    categoryLabel: "1kg Format",
    price: 42900,
    boxQty: 6,
    boxPrice: 257400,
    weight: "1kg",
    unit: "quti",
    image: "/products/p12_img2.jpeg",
    images: ["/products/p12_img2.jpeg", "/products/p12_img4.jpeg"],
    description: "Gilos va shokolad aralash mevali marojni, 1kg",
    descriptionFull: "A delightful blend of sweet cherries and rich chocolate in a smooth ice cream base.",
    tags: ["gilos", "shokolad", "meva", "1kg"],
    isPremium: true,
  },

  // ═══════════════════════════════════════════════
  //  OVQAT (Food Products)
  // ═══════════════════════════════════════════════

  // ─── Сырок (Glazed Cheese Bars) ───
  {
    id: "syrok-assorted",
    name: "Musa Syrок (Glazirlangan)",
    brand: "Musa",
    category: "ovqat",
    categoryLabel: "Syrok",
    price: 3000,
    boxQty: 80,
    boxPrice: 240000,
    weight: "40g",
    unit: "dona",
    image: "/products/p20_img1.jpeg",
    images: ["/products/p20_img1.jpeg", "/products/p20_img2.jpeg"],
    description: "Glazirlangan tvorog barlar — 13 xil ta'm: shaftoli, banan, olcha va boshqalar",
    descriptionFull: "Classic glazed curd cheese bars in 13 varieties: Shaftoli, Banan, Olcha, Kokos, Qulupnay, Gilos, Qaymoq, O'rmon mevasi, Olma, Qahva, Shokolad, Meva bo'laklari, Nainsiz. Har biri toza tvorogdan tayyorlangan.",
    tags: ["tvorog", "glazirlangan", "assorted"],
    isNew: true,
  },
  // ─── Jiyan (Cheese in Cone) ───
  {
    id: "jiyan-cone",
    name: "Jiyan Syrki v Rojke",
    brand: "Jiyan",
    category: "ovqat",
    categoryLabel: "Syrki Konusda",
    price: 8000,
    boxQty: 16,
    boxPrice: 128000,
    weight: "90g",
    unit: "dona",
    image: "/products/p21_img1.jpeg",
    images: ["/products/p21_img1.jpeg", "/products/p21_img2.jpeg"],
    description: "Kremli tvorog 5 ta waffle konusda — mazali va qulay",
    descriptionFull: "5 miniature cheese cones in one pack — creamy glazed curd in crispy waffle cones. A unique and fun format perfect for kids and adults alike.",
    tags: ["tvorog", "konus", "waffle"],
    isNew: true,
  },
  // ─── Chocolitto ───
  {
    id: "chocolitto-450",
    name: "Chocolitto Kakao-Bodom Pasta 450g",
    brand: "Chocolitto",
    category: "ovqat",
    categoryLabel: "Kakao Pasta",
    price: 26500,
    boxQty: 12,
    boxPrice: 318000,
    weight: "450g",
    unit: "quti",
    image: "/products/p22_img2.jpeg",
    images: ["/products/p22_img2.jpeg", "/products/p22_img1.jpeg"],
    description: "Kakao-bodom yog'li pasta, nonushta uchun ideal",
    descriptionFull: "Smooth and rich hazelnut cocoa spread — like Nutella but made by MUSA. Perfect for breakfast, toasts, crepes, and desserts. Without palm oil.",
    tags: ["kakao", "bodom", "pasta", "nonushta"],
    isNew: true,
  },
  {
    id: "chocolitto-250",
    name: "Chocolitto Kakao-Bodom Pasta 250g",
    brand: "Chocolitto",
    category: "ovqat",
    categoryLabel: "Kakao Pasta",
    price: 15600,
    boxQty: 18,
    boxPrice: 280800,
    weight: "250g",
    unit: "quti",
    image: "/products/p22_img3.jpeg",
    images: ["/products/p22_img3.jpeg", "/products/p22_img1.jpeg"],
    description: "Kakao-bodom pasta, kichik hajm",
    descriptionFull: "The same rich hazelnut cocoa spread in a compact 250g pack. Great for home use and gifting.",
    tags: ["kakao", "bodom", "pasta"],
  },
  // ─── Chuchvara / Pelmeni ───
  {
    id: "chuchvara-beef-500",
    name: "Musa Chuchvara (Go'sht) 500g",
    brand: "Musa",
    category: "ovqat",
    categoryLabel: "Chuchvara",
    price: 22600,
    boxQty: 15,
    boxPrice: 339000,
    weight: "500g",
    unit: "quti",
    image: "/products/p23_img2.jpeg",
    images: ["/products/p23_img2.jpeg", "/products/p23_img1.jpeg"],
    description: "Mol go'shtli chuchvara, yuqori sifatli go'sht",
    descriptionFull: "Traditional Uzbek chuchvara made from premium beef. Handcrafted shape, rich filling, perfect for boiling or frying. From the freshest cuts of beef.",
    tags: ["chuchvara", "go'sht", "halol"],
    isNew: true,
  },
  {
    id: "chuchvara-beef-1kg",
    name: "Musa Chuchvara (Go'sht) 1kg",
    brand: "Musa",
    category: "ovqat",
    categoryLabel: "Chuchvara",
    price: 43800,
    boxQty: 8,
    boxPrice: 350400,
    weight: "1kg",
    unit: "quti",
    image: "/products/p23_img3.jpeg",
    images: ["/products/p23_img3.jpeg", "/products/p23_img1.jpeg"],
    description: "Mol go'shtli chuchvara — yirik hajm, 1kg",
    descriptionFull: "1kg pack of premium beef chuchvara. Ideal for family meals and restaurants. Same quality filling, bigger pack.",
    tags: ["chuchvara", "go'sht", "1kg", "halol"],
  },
  {
    id: "chuchvara-lamb",
    name: "Musa Chuchvara (Qo'y Go'shti)",
    brand: "Musa",
    category: "ovqat",
    categoryLabel: "Chuchvara",
    price: 29500,
    boxQty: 0,
    boxPrice: 0,
    weight: "750g",
    unit: "quti",
    image: "/products/p23_img5.jpeg",
    images: ["/products/p23_img5.jpeg", "/products/p23_img1.jpeg"],
    description: "Qo'y go'shtli an'anaviy chuchvara, 750g",
    descriptionFull: "Traditional lamb chuchvara with authentic taste. Rich, tender filling from premium lamb. A classic Uzbek delicacy.",
    tags: ["chuchvara", "qo'y go'shti", "an'anaviy"],
    isPremium: true,
  },
  {
    id: "adnan-chuchvara-500",
    name: "Adnan Chuchvara 500g",
    brand: "Adnan",
    category: "ovqat",
    categoryLabel: "Chuchvara",
    price: 14100,
    boxQty: 15,
    boxPrice: 211500,
    weight: "500g",
    unit: "quti",
    image: "/products/p24_img2.jpeg",
    images: ["/products/p24_img2.jpeg", "/products/p24_img1.jpeg"],
    description: "Adnan brendidan go'shtli chuchvara, 500g",
    descriptionFull: "Premium beef chuchvara from Adnan brand. Made from fresh meat with traditional spices.",
    tags: ["chuchvara", "go'sht", "adnan"],
  },
  {
    id: "vareniki-potato",
    name: "Musa Vareniki Kartoshkali",
    brand: "Musa",
    category: "ovqat",
    categoryLabel: "Vareniki",
    price: 9000,
    boxQty: 15,
    boxPrice: 135000,
    weight: "500g",
    unit: "quti",
    image: "/products/p24_img7.jpeg",
    images: ["/products/p24_img7.jpeg", "/products/p24_img1.jpeg"],
    description: "Kartoshkali an'anaviy vareniki, 500g",
    descriptionFull: "Traditional potato-filled dumplings (vareniki). Soft dough with a creamy potato filling. Serve boiled with butter or sour cream.",
    tags: ["vareniki", "kartoshka", "vegetarian"],
    isNew: true,
  },
  {
    id: "alladin-chuchvara",
    name: "Alladin Premium Chuchvara 500g",
    brand: "Alladin",
    category: "ovqat",
    categoryLabel: "Chuchvara",
    price: 23000,
    boxQty: 15,
    boxPrice: 345000,
    weight: "500g",
    unit: "quti",
    image: "/products/p25_img2.jpeg",
    images: ["/products/p25_img2.jpeg", "/products/p25_img1.jpeg"],
    description: "Alladin premium go'shtli chuchvara, halol",
    descriptionFull: "Premium Alladin brand beef chuchvara. Halal certified, made from fresh beef with authentic Uzbek spices.",
    tags: ["chuchvara", "go'sht", "premium", "halol"],
    isPremium: true,
  },
  {
    id: "chuchvara-chicken",
    name: "Musa Chuchvara Tovuq Go'shti",
    brand: "Musa",
    category: "ovqat",
    categoryLabel: "Chuchvara",
    price: 15600,
    boxQty: 15,
    boxPrice: 234000,
    weight: "500g",
    unit: "quti",
    image: "/products/p25_img4.jpeg",
    images: ["/products/p25_img4.jpeg", "/products/p25_img1.jpeg"],
    description: "Tovuq go'shtli yengil chuchvara",
    descriptionFull: "Lighter chicken chuchvara for those who prefer a leaner filling. Tender chicken with aromatic herbs.",
    tags: ["chuchvara", "tovuq", "yengil"],
    isNew: true,
  },
  // ─── Somsa ───
  {
    id: "somsa-meat",
    name: "Musa Somsa (Go'sht) 780g",
    brand: "Musa",
    category: "ovqat",
    categoryLabel: "Somsa",
    price: 44500,
    boxQty: 8,
    boxPrice: 356000,
    weight: "780g",
    unit: "quti",
    image: "/products/p26_img1.jpeg",
    images: ["/products/p26_img1.jpeg", "/products/p26_img3.jpeg"],
    description: "Go'shtli qatlama somsa — 12 dona, pishirish oson",
    descriptionFull: "Traditional Uzbek layered samsa with beef filling. 12 pieces per pack. Bake in oven at 200°C for 25-30 minutes for a crispy, golden result.",
    tags: ["somsa", "go'sht", "qatlama", "halol"],
    isNew: true,
  },
  {
    id: "somsa-chicken",
    name: "Musa Somsa (Tovuq) 780g",
    brand: "Musa",
    category: "ovqat",
    categoryLabel: "Somsa",
    price: 30000,
    boxQty: 8,
    boxPrice: 240000,
    weight: "780g",
    unit: "quti",
    image: "/products/p26_img2.jpeg",
    images: ["/products/p26_img2.jpeg", "/products/p26_img3.jpeg"],
    description: "Tovuq go'shtli qatlama somsa — 12 dona",
    descriptionFull: "Layered samsa with seasoned chicken filling. 12 pieces, ready to bake. Lighter than beef, equally delicious.",
    tags: ["somsa", "tovuq", "qatlama"],
    isNew: true,
  },
  {
    id: "somsa-potato",
    name: "Musa Somsa (Kartoshka) 780g",
    brand: "Musa",
    category: "ovqat",
    categoryLabel: "Somsa",
    price: 25000,
    boxQty: 8,
    boxPrice: 200000,
    weight: "780g",
    unit: "quti",
    image: "/products/p26_img4.jpeg",
    images: ["/products/p26_img4.jpeg", "/products/p26_img3.jpeg"],
    description: "Kartoshkali somsa — vegetarian variant",
    descriptionFull: "Vegetarian samsa with a delicious potato and onion filling. Crispy layers, soft filling. 12 pieces per pack.",
    tags: ["somsa", "kartoshka", "vegetarian"],
  },
  {
    id: "qatlama",
    name: "Adnan Qatlama 500g",
    brand: "Adnan",
    category: "ovqat",
    categoryLabel: "Qatlama",
    price: 12000,
    boxQty: 12,
    boxPrice: 144000,
    weight: "500g",
    unit: "quti",
    image: "/products/p26_img5.jpeg",
    images: ["/products/p26_img5.jpeg"],
    description: "An'anaviy qatlama non, 5 ta",
    descriptionFull: "Traditional layered flatbread (qatlama). Flaky, buttery, and delicious. Heat in a pan or oven. 5 pieces per pack.",
    tags: ["qatlama", "non", "an'anaviy"],
  },
  // ─── Lagman ───
  {
    id: "lagman-500",
    name: "Musa Lagman 500g",
    brand: "Musa",
    category: "ovqat",
    categoryLabel: "Lagman",
    price: 6850,
    boxQty: 10,
    boxPrice: 68500,
    weight: "500g",
    unit: "quti",
    image: "/products/p28_img1.jpeg",
    images: ["/products/p28_img1.jpeg", "/products/p28_img2.jpeg"],
    description: "An'anaviy qo'lda tortilgan lagman, 500g",
    descriptionFull: "Hand-pulled Uzbek lagman noodles. Ready to boil and serve with any sauce or broth. Made from wheat flour without preservatives.",
    tags: ["lagman", "osh", "qo'l tortilgan"],
    isNew: true,
  },
  {
    id: "lavash",
    name: "Musa Lavash 480g",
    brand: "Musa",
    category: "ovqat",
    categoryLabel: "Non",
    price: 7700,
    boxQty: 0,
    boxPrice: 0,
    weight: "480g",
    unit: "quti",
    image: "/products/p28_img4.jpeg",
    images: ["/products/p28_img4.jpeg"],
    description: "Yupqa lavash non — 3 ta, ko'p maqsadli",
    descriptionFull: "Soft thin lavash bread — 3 sheets per pack. Use for wraps, rolls, pizza, or serve with any meal.",
    tags: ["lavash", "non", "yupqa"],
  },
  {
    id: "pizza-dough",
    name: "Musa Pizza Xamiri 550g",
    brand: "Musa",
    category: "ovqat",
    categoryLabel: "Pizza Xamiri",
    price: 15000,
    boxQty: 5,
    boxPrice: 75000,
    weight: "550g",
    unit: "quti",
    image: "/products/p28_img5.jpeg",
    images: ["/products/p28_img5.jpeg", "/products/p28_img6.jpeg"],
    description: "Tayyor pizza xamiri — 2 ta, faqat yoying va pishing",
    descriptionFull: "Ready-to-use pizza dough — just roll out, top with your ingredients, and bake. 2 dough balls per pack. Perfect for homemade pizza nights.",
    tags: ["pizza", "xamir", "tayyor"],
    isNew: true,
  },
  // ─── Kotlety / Meatballs ───
  {
    id: "kotlety-beef-500",
    name: "Musa Kotleta (Go'sht) 500g",
    brand: "Musa",
    category: "ovqat",
    categoryLabel: "Kotleta",
    price: 40200,
    boxQty: 12,
    boxPrice: 482400,
    weight: "500g",
    unit: "quti",
    image: "/products/p29_img1.jpeg",
    images: ["/products/p29_img1.jpeg", "/products/p29_img2.jpeg"],
    description: "Mol go'shtli premium kotleta, tayyor qilish oson",
    descriptionFull: "Premium beef patties ready to fry or grill. Made from fresh beef with onion and natural spices. No fillers or artificial additives.",
    tags: ["kotleta", "go'sht", "premium"],
    isPremium: true,
  },
  {
    id: "kotlety-chicken",
    name: "Musa Kotleta Tovuq 400g",
    brand: "Musa",
    category: "ovqat",
    categoryLabel: "Kotleta",
    price: 15200,
    boxQty: 12,
    boxPrice: 182400,
    weight: "400g",
    unit: "quti",
    image: "/products/p29_img3.jpeg",
    images: ["/products/p29_img3.jpeg", "/products/p29_img2.jpeg"],
    description: "Tovuq go'shtli yengil kotleta",
    descriptionFull: "Light chicken patties — lower in fat, high in protein. Great for healthy meals. Fry or bake as desired.",
    tags: ["kotleta", "tovuq", "yengil"],
    isNew: true,
  },
  {
    id: "tefteli-musa",
    name: "Musa Tefteli 480g",
    brand: "Musa",
    category: "ovqat",
    categoryLabel: "Tefteli",
    price: 61200,
    boxQty: 10,
    boxPrice: 612000,
    weight: "480g",
    unit: "quti",
    image: "/products/p29_img5.jpeg",
    images: ["/products/p29_img5.jpeg", "/products/p29_img4.jpeg"],
    description: "Premium mol go'shtli tefteli — 6 ta dona",
    descriptionFull: "Large premium beef meatballs — 6 pieces per pack. Rich in meat content, seasoned with traditional spices. Perfect for tomato sauce, soups, or grilling.",
    tags: ["tefteli", "go'sht", "premium"],
    isPremium: true,
  },
  // ─── Blinchiki ───
  {
    id: "blinchiki-farsh",
    name: "Musa Blinchiki Go'shtli 300g",
    brand: "Musa",
    category: "ovqat",
    categoryLabel: "Blinchiki",
    price: 19200,
    boxQty: 16,
    boxPrice: 307200,
    weight: "300g",
    unit: "quti",
    image: "/products/p30_img4.jpeg",
    images: ["/products/p30_img4.jpeg", "/products/p30_img1.jpeg"],
    description: "Go'shtli blinchiklar — 6 ta, qovurishga tayyor",
    descriptionFull: "Thin crepes filled with seasoned beef. 6 pieces per pack. Pan-fry for a golden crispy finish. Quick and satisfying meal.",
    tags: ["blinchiki", "go'sht", "tayyor"],
    isNew: true,
  },
  {
    id: "blinchiki-tvorog",
    name: "Musa Blinchiki Tvorogli",
    brand: "Musa",
    category: "ovqat",
    categoryLabel: "Blinchiki",
    price: 10700,
    boxQty: 14,
    boxPrice: 149800,
    weight: "200g",
    unit: "quti",
    image: "/products/p30_img7.jpeg",
    images: ["/products/p30_img7.jpeg", "/products/p30_img1.jpeg"],
    description: "Tvorogli an'anaviy blinchiklar — 10 ta",
    descriptionFull: "Traditional cottage cheese-filled crepes. 10 pieces per pack. Serve warm with sour cream or jam.",
    tags: ["blinchiki", "tvorog", "vegetarian"],
  },
  // ─── Farsh / Minced Meat ───
  {
    id: "farsh-qiyma-300",
    name: "Musa Qiyma (Go'sht) 300g",
    brand: "Musa",
    category: "ovqat",
    categoryLabel: "Qiyma",
    price: 32500,
    boxQty: 0,
    boxPrice: 0,
    weight: "300g",
    unit: "quti",
    image: "/products/p31_img2.jpeg",
    images: ["/products/p31_img2.jpeg", "/products/p31_img1.jpeg"],
    description: "Toza mol go'shtidan tayyorlangan qiyma, 300g",
    descriptionFull: "Fresh premium minced beef — prepared from high-quality cuts. Ideal for kotleta, tefteli, manti, or any dish requiring minced meat.",
    tags: ["qiyma", "go'sht", "toza"],
    isNew: true,
  },
  {
    id: "farsh-qiyma-500",
    name: "Musa Qiyma (Go'sht) 500g",
    brand: "Musa",
    category: "ovqat",
    categoryLabel: "Qiyma",
    price: 53000,
    boxQty: 0,
    boxPrice: 0,
    weight: "500g",
    unit: "quti",
    image: "/products/p31_img3.jpeg",
    images: ["/products/p31_img3.jpeg", "/products/p31_img1.jpeg"],
    description: "Toza mol go'shtidan tayyorlangan qiyma, 500g",
    descriptionFull: "Premium fresh minced beef in a 500g pack. No preservatives, no additives. Use immediately or freeze.",
    tags: ["qiyma", "go'sht", "toza"],
  },
];

export const OPERATOR = {
  name: "Musa Operator",
  phone: "+998 71 246 02 33",
  email: "Frozenfoods@bk.ru",
  address: "100179, Kamarniso Street, Almazar District, Tashkent",
  website: "www.musa-servis.uz",
};

export function getProductById(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}
